// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2JLHoKifpioW56ilO9vzCPeNKwwy50BE',
    appId: '1:440403850503:web:1c1b20278764fd429a41a2',
    messagingSenderId: '440403850503',
    projectId: 'brivora-c5aa8',
    authDomain: 'brivora-c5aa8.firebaseapp.com',
    storageBucket: 'brivora-c5aa8.firebasestorage.app',
    measurementId: 'G-SKCVF3FREK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GP5IobfBpyTgsQ2im2uMU4GsNh7STyk',
    appId: '1:440403850503:android:eb7e5edb9ea994119a41a2',
    messagingSenderId: '440403850503',
    projectId: 'brivora-c5aa8',
    storageBucket: 'brivora-c5aa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD40fwBGsTUYt9OZla8I4iIEc7cYpyxqo4',
    appId: '1:440403850503:ios:34563047e2bb398e9a41a2',
    messagingSenderId: '440403850503',
    projectId: 'brivora-c5aa8',
    storageBucket: 'brivora-c5aa8.firebasestorage.app',
    iosBundleId: 'com.example.brivora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD40fwBGsTUYt9OZla8I4iIEc7cYpyxqo4',
    appId: '1:440403850503:ios:34563047e2bb398e9a41a2',
    messagingSenderId: '440403850503',
    projectId: 'brivora-c5aa8',
    storageBucket: 'brivora-c5aa8.firebasestorage.app',
    iosBundleId: 'com.example.brivora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2JLHoKifpioW56ilO9vzCPeNKwwy50BE',
    appId: '1:440403850503:web:f0839b845906db429a41a2',
    messagingSenderId: '440403850503',
    projectId: 'brivora-c5aa8',
    authDomain: 'brivora-c5aa8.firebaseapp.com',
    storageBucket: 'brivora-c5aa8.firebasestorage.app',
    measurementId: 'G-LQXDPEQ36F',
  );
}
